### ISSUE TITLE
Unable to parse AccountAddress (must be hex string of length 16)

### ISSUE THREAD

**Issue by hafizsheetab** [overmind-xyz/diamond-clicker#2]
So I have wrote the code and trying to test it using 
`move test`
It shows the error generated from the Move.toml file 

Error: Error parsing '[addresses]' section of manifest

Caused by:
    0: Invalid address '0xe9fa01aaa1a483c6c598d470ae9b8174226590499b25812d8f0e86192a3b8711' encountered.
    1: Unable to parse AccountAddress (must be hex string of length 16)

**Comment by hafizsheetab** [comment]
I changed the address and made it smaller. then the git test works but it shows the following errors


error[E01002]: unexpected token
   ┌─ /home/sheetab/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/../aptos-stdlib/sources/string_utils.move:65:5
   │
65 │     inline fun list1<T0>(a: T0): Cons<T0, NIL> { cons(a, nil()) }
   │     ^^^^^^
   │     │
   │     Unexpected 'inline'
   │     Expected a module member: 'spec', 'use', 'friend', 'const', 'fun', or 'struct'

error[E01002]: unexpected token
   ┌─ /home/sheetab/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/../aptos-stdlib/sources/debug.move:13:5
   │
13 │     inline fun format<T>(x: &T): String {
   │     ^^^^^^
   │     │
   │     Unexpected 'inline'
   │     Expected a module member: 'spec', 'use', 'friend', 'const', 'fun', or 'struct'

error[E01002]: unexpected token
   ┌─ ./sources/diamond_clicker.move:52:13
   │
50 │         move_to(account, GameStore {
   │                                    - To match this '{'
51 │             diamonds: 0
52 │             upgrades: vector::empty<Upgrade>()
   │             ^ Expected '}'

error[E01002]: unexpected token
   ┌─ /home/sheetab/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/../aptos-stdlib/sources/math64.move:31:12
   │
31 │     public inline fun mul_div(a: u64, b: u64, c: u64): u64 {
   │            ^^^^^^
   │            │
   │            Unexpected 'inline'
   │            Expected a module member: 'spec', 'use', 'friend', 'const', 'fun', or 'struct'

error[E01002]: unexpected token
    ┌─ /home/sheetab/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/sources/fungible_asset.move:566:5
    │
566 │     inline fun borrow_fungible_metadata<T: key>(
    │     ^^^^^^
    │     │
    │     Unexpected 'inline'
    │     Expected a module member: 'spec', 'use', 'friend', 'const', 'fun', or 'struct'

error[E01002]: unexpected token
    ┌─ /home/sheetab/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/sources/delegation_pool.move:855:5
    │
855 │     inline fun borrow_mut_used_voting_power(governance_records: &mut GovernanceRecords, voter: address, proposal_id: u64): &mut u64 {
    │     ^^^^^^
    │     │
    │     Unexpected 'inline'
    │     Expected a module member: 'spec', 'use', 'friend', 'const', 'fun', or 'struct'

error[E01002]: unexpected token
   ┌─ /home/sheetab/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/../aptos-stdlib/sources/math128.move:33:12
   │
33 │     public inline fun mul_div(a: u128, b: u128, c: u128): u128 {
   │            ^^^^^^
   │            │
   │            Unexpected 'inline'
   │            Expected a module member: 'spec', 'use', 'friend', 'const', 'fun', or 'struct'

error[E01002]: unexpected token
    ┌─ /home/sheetab/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/../aptos-stdlib/../move-stdlib/sources/option.move:268:12
    │
268 │     public inline fun for_each<Element>(o: Option<Element>, f: |Element|) {
    │            ^^^^^^
    │            │
    │            Unexpected 'inline'
    │            Expected a module member: 'spec', 'use', 'friend', 'const', 'fun', or 'struct'

error[E01002]: unexpected token
    ┌─ /home/sheetab/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/../aptos-stdlib/../move-stdlib/sources/vector.move:182:12
    │
182 │     public inline fun find<Element>(v: &vector<Element>, f: |&Element|bool): (bool, u64) {
    │            ^^^^^^
    │            │
    │            Unexpected 'inline'
    │            Expected a module member: 'spec', 'use', 'friend', 'const', 'fun', or 'struct'

error[E01002]: unexpected token
    ┌─ /home/sheetab/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/../aptos-stdlib/sources/simple_map.move:165:12
    │
165 │     public inline fun destroy<Key: store, Value: store>(
    │            ^^^^^^
    │            │
    │            Unexpected 'inline'
    │            Expected a module member: 'spec', 'use', 'friend', 'const', 'fun', or 'struct'

sheetab@sheetab-VirtualBox:~/Desktop/diamond-clicker$ error[E01002]: unexpected token
   ┌─ /home/sheetab/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/../aptos-stdlib/sources/string_utils.move:65:5
   │
65 │     inline fun list1<T0>(a: T0): Cons<T0, NIL> { cons(a, nil()) }
   │     ^^^^^^
   │     │
   │     Unexpected 'inline'
   │     Expected a module member: 'spec', 'use', 'friend', 'const', 'fun', or 'struct'

error[E01002]: unexpected token
   ┌─ /home/sheetab/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/../aptos-stdlib/sources/debug.move:13:5
   │
13 │     inline fun format<T>(x: &T): String {
   │     ^^^^^^
   │     │
   │     Unexpected 'inline'
   │     Expected a module member: 'spec', 'use', 'friend', 'const', 'fun', or 'struct'

error[E01002]: unexpected token
   ┌─ ./sources/diamond_clicker.move:52:13
   │
50 │         move_to(account, GameStore {
   │                                    - To match this '{'
51 │             diamonds: 0
52 │             upgrades: vector::empty<Upgrade>()
   │             ^ Expected '}'

error[E01002]: unexpected token
   ┌─ /home/sheetab/.move/https___github_co

**Comment by hafizsheetab** [comment]
It also shows this error for the code that i am not allowed to rewrite

error[E01002]: unexpected token
    ┌─ ./sources/diamond_clicker.move:158:5
    │
158 │     inline fun test_click_loop(signer: &signer, amount: u64) acquires GameStore {
    │     ^^^^^^
    │     │
    │     Unexpected 'inline'
    │     Expected a module member: 'spec', 'use', 'friend', 'const', 'fun', or 'struct'

**Comment by Qwerky7835** [comment]
Hi @hafizsheetab,

The correct CLI command is `aptos move test`. To confirm, you are using the Aptos CLI version 1.0.12?

**Comment by hafizsheetab** [comment]
no i am using move-cli.
It shows in the tutorial to install move-cli hence i did.

**Comment by Qwerky7835** [comment]
Please download this binary: https://github.com/aptos-labs/aptos-core/releases/tag/aptos-cli-v1.0.13

Can you indicate the exact location where it mentioned install move-cli?

**Comment by hafizsheetab** [comment]
> Please download this binary: https://github.com/aptos-labs/aptos-core/releases/tag/aptos-cli-v1.0.13
> 
> Can you indicate the exact location where it mentioned install move-cli?

Here is the tutorial
https://github.com/move-language/move/blob/main/language/documentation/tutorial/README.md

**Comment by Qwerky7835** [comment]
Ah yes. That is the Sui Move github. You want to Aptos one. These chains have all implemented Move differently and Sui addresses are different from Aptos ones. Please let me know if you can successfully compile and I will close the issue.

**Comment by hafizsheetab** [comment]
Yes, I was finally able to complete it 
![image](https://github.com/overmind-xyz/diamond-clicker/assets/56652043/06ccf888-becf-424d-98a3-125ec2db62eb)
the tutorials and move book needs to be updated i think. there is not much talking about the borrowing mechanisms. Although it follows the rust rules but there are a bit catches here and there
Thank you @Qwerky7835 for the support
